-- Schema for Digital Marketing & Ecommerce Performance
CREATE TABLE IF NOT EXISTS marketing_campaigns (
    ID INTEGER PRIMARY KEY,
    Year_Birth INTEGER,
    Education TEXT,
    Marital_Status TEXT,
    Income REAL,
    Kidhome INTEGER,
    Teenhome INTEGER,
    Dt_Customer TEXT,
    Recency INTEGER,
    MntWines REAL,
    MntFruits REAL,
    MntMeatProducts REAL,
    MntFishProducts REAL,
    MntSweetProducts REAL,
    MntGoldProds REAL,
    NumDealsPurchases INTEGER,
    NumWebPurchases INTEGER,
    NumCatalogPurchases INTEGER,
    NumStorePurchases INTEGER,
    NumWebVisitsMonth INTEGER,
    AcceptedCmp3 INTEGER,
    AcceptedCmp4 INTEGER,
    AcceptedCmp5 INTEGER,
    AcceptedCmp1 INTEGER,
    AcceptedCmp2 INTEGER,
    Complain INTEGER,
    Response INTEGER,
    Age INTEGER,
    Children INTEGER,
    Total_Spend REAL,
    Total_Purchases INTEGER,
    Total_Accepted_Cmp INTEGER
);
